name: "bert"
backend: "python"
input [
  {
    name: "text_input"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
output [
  {
    name: "output"
    data_type: TYPE_STRING
    dims: [ -1 ]
  }
]
instance_group [
  {
    kind: KIND_CPU
  }
]
